SELECT 
USERS.USER_LOGIN AS USERNAME, 
TASK.TASK_INITDATE AS INITDATE,
TASK.TASK_INITHOUR AS INITTIME,
TASKTYPE_NAME AS TYPE,
TASKSTATE_NAME AS STATE
FROM <ownerdatabase>.DBO.TASK
INNER JOIN <ownerdatabase>.DBO.USERS
ON TASK.TASK_ID_USEROWNER = USERS.USER_ID 
INNER JOIN <ownerdatabase>.DBO.TYPETASK_TYPE
ON TASK.TASK_ID_TASKTYPE = TYPETASK_TYPE.ID_TASKTYPE
INNER JOIN <ownerdatabase>.DBO.TYPETASK_STATE
ON TASK.TASK_ID_STATUS = TYPETASK_STATE.ID_TYPETASK_STATE
WHERE TASK_TYPE = 3
AND TASK_COMPANY_ID = <company>
AND TASK_ID_USEROWNER BETWEEN 1 AND 10
AND TASK_INITDATE BETWEEN CONVERT(DATETIME, '2009-01-01', 102) AND CONVERT(DATETIME, '2009-12-31', 102)
AND TASK_ID_TASKTYPE BETWEEN 1 AND 10
AND TASK_ID_STATUS BETWEEN 1 AND 10
ORDER BY USERNAME, INITDATE, INITTIME

SELECT 
POTENTIALCUSTOMERS.COD_CLIENT AS CODE,
POTENTIALCUSTOMERS.RAZON_SOCI AS LEGALNAME,
POTENTIALCUSTOMERS.DOMICILIO AS ADRESS,
POTENTIALCUSTOMERS.LOCALIDAD AS CITY,
STATES.NOMBRE_PRO AS STATE,
ZONES.NOMBRE_ZON AS ZONE,
EMPLOYEES.NOMBRE_VEN AS EMPLOYEE
FROM <ownerdatabase>.DBO.POTENTIALCUSTOMERS
INNER JOIN <database>.DBO.GVA18 STATES
ON POTENTIALCUSTOMERS.COD_PROVIN = STATES.COD_PROVIN COLLATE Latin1_General_BIN
INNER JOIN <database>.DBO.GVA05 ZONES
ON POTENTIALCUSTOMERS.COD_ZONA = ZONES.COD_ZONA COLLATE Latin1_General_BIN
INNER JOIN <database>.DBO.GVA23 EMPLOYEES
ON POTENTIALCUSTOMERS.COD_VENDED = EMPLOYEES.COD_VENDED COLLATE Latin1_General_BIN
WHERE ID_COMPANY = <company>
AND COD_TANGO <> ''
AND POTENTIALCUSTOMERS.COD_CLIENT NOT IN
(
SELECT CUSTOMERCODE COLLATE Latin1_General_BIN
FROM <ownerdatabase>.DBO.CUSTOMERSDELETED
WHERE ID_COMPANY = <company>
AND PROCESSED = 1
)
AND POTENTIALCUSTOMERS.COD_CLIENT BETWEEN '' AND 'ZZ'
AND POTENTIALCUSTOMERS.COD_ZONA BETWEEN '' AND 'ZZ'
AND POTENTIALCUSTOMERS.COD_PROVIN BETWEEN '' AND 'ZZ' 
AND POTENTIALCUSTOMERS.COD_VENDED BETWEEN '' AND 'ZZ'

SELECT 
ACTIONS.ACTION_USER AS USERID,
USERS.USER_LOGIN USERNAME,
ACTIONPARAMETERS.PARAMETER_VALUE CUSTOMERCODE,
POTENTIALCUSTOMERS.RAZON_SOCI CUSTOMERNAME,
ACTIONS.ACTION_DATE_DATAENTRY AS INITDATE
FROM <ownerdatabase>.DBO.ACTIONS
INNER JOIN <ownerdatabase>.DBO.USERS
ON ACTIONS.ACTION_USER = USERS.USER_ID
INNER JOIN <ownerdatabase>.DBO.ACTIONPARAMETERS
ON ACTIONS.ACTION_ID = ACTIONPARAMETERS.ACTION_ID
AND ACTIONPARAMETERS.PARAMETER_NAME = '@CODE'
INNER JOIN <ownerdatabase>.DBO.POTENTIALCUSTOMERS
ON ACTIONPARAMETERS.PARAMETER_VALUE = POTENTIALCUSTOMERS.COD_CLIENT COLLATE Latin1_General_BIN
WHERE ACTIONS.ACTION_ID_OBJECTTYPE = 1
AND ACTIONS.ACTION_SQLNAME = 'CRM.dbo.sp_InsertCustomer'
AND POTENTIALCUSTOMERS.COD_TANGO = ''
AND POTENTIALCUSTOMERS.ID_COMPANY = <company>
AND ACTIONS.ACTION_USER BETWEEN <userfrom> AND <userto>
AND ACTIONS.ACTION_DATE_DATAENTRY BETWEEN CONVERT(DATETIME, '<datefrom>', 102) AND CONVERT(DATETIME, '<dateto>', 102) 
AND ACTIONPARAMETERS.PARAMETER_VALUE BETWEEN '<customerfrom>' AND '<customerto>'


SELECT 
ACTIONS.ACTION_USER AS USERID,
USERS.USER_LOGIN USERNAME,
ACTIONPARAMETERS.PARAMETER_VALUE CUSTOMERCODE,
POTENTIALCUSTOMERS.RAZON_SOCI CUSTOMERNAME,
ACTIONS.ACTION_DATE_DATAENTRY AS INITDATE,
POTENTIALCUSTOMERS.COD_TANGO AS TGCODE,
POTENTIALCUSTOMERS.FECHA_TANGO AS TGDATE,
DATEDIFF(day, ACTIONS.ACTION_DATE_DATAENTRY, POTENTIALCUSTOMERS.FECHA_TANGO) AS DAYS
FROM <ownerdatabase>.DBO.ACTIONS
INNER JOIN <ownerdatabase>.DBO.USERS
ON ACTIONS.ACTION_USER = USERS.USER_ID
INNER JOIN <ownerdatabase>.DBO.ACTIONPARAMETERS
ON ACTIONS.ACTION_ID = ACTIONPARAMETERS.ACTION_ID
AND ACTIONPARAMETERS.PARAMETER_NAME = '@CODE'
INNER JOIN <ownerdatabase>.DBO.POTENTIALCUSTOMERS
ON ACTIONPARAMETERS.PARAMETER_VALUE = POTENTIALCUSTOMERS.COD_CLIENT COLLATE Latin1_General_BIN
WHERE ACTIONS.ACTION_ID_OBJECTTYPE = 1
AND ACTIONS.ACTION_SQLNAME = '<ownerdatabase>.dbo.sp_InsertCustomer'
AND POTENTIALCUSTOMERS.COD_TANGO <> ''
AND POTENTIALCUSTOMERS.ID_COMPANY = <company>
AND ACTIONS.ACTION_USER BETWEEN <userfrom> AND <userto>
AND ACTIONS.ACTION_DATE_DATAENTRY BETWEEN CONVERT(DATETIME, '<datefrom>', 102) AND CONVERT(DATETIME, '<dateto>', 102)
AND POTENTIALCUSTOMERS.FECHA_TANGO BETWEEN CONVERT(DATETIME, '<tangofrom>', 102) AND CONVERT(DATETIME, '<tangoto>', 102) 
AND ACTIONPARAMETERS.PARAMETER_VALUE BETWEEN '<customerfrom>' AND '<customerto>'


SELECT 
CUSTOMERSDELETED.USERID AS USERID,
USERS.USER_LOGIN AS USERNAME,
CUSTOMERSDELETED.CUSTOMERCODE,
POTENTIALCUSTOMERS.RAZON_SOCI AS CUSTOMERNAME,
CUSTOMERSDELETED.CANCELDATE,
CUSTOMERSDELETED.REASSONCODE,
TYPECUSTOMER_CANCELREASSONS.CANCELREASSON_NAME AS REASSONNAME,
(CASE WHEN PROCESSED = 0 THEN 'PENDIENTE' ELSE 'PROCESADO' END) AS STATUS
FROM <ownerdatabase>.DBO.CUSTOMERSDELETED
INNER JOIN <ownerdatabase>.DBO.USERS
ON CUSTOMERSDELETED.USERID = USERS.USER_ID
INNER JOIN <ownerdatabase>.DBO.POTENTIALCUSTOMERS
ON CUSTOMERSDELETED.CUSTOMERCODE = POTENTIALCUSTOMERS.COD_CLIENT COLLATE Latin1_General_BIN
AND CUSTOMERSDELETED.POTENTIALCUSTOMER <> 0
INNER JOIN <ownerdatabase>.DBO.TYPECUSTOMER_CANCELREASSONS
ON CUSTOMERSDELETED.REASSONCODE = TYPECUSTOMER_CANCELREASSONS.ID_CUSTOMERCANCELREASSON
WHERE CUSTOMERSDELETED.ID_COMPANY = <company>
AND CUSTOMERSDELETED.USERID BETWEEN <userfrom> AND <userto>
AND CUSTOMERSDELETED.CANCELDATE BETWEEN CONVERT(DATETIME, '<datefrom>', 102) AND CONVERT(DATETIME, '<dateto>', 102) 
AND CUSTOMERSDELETED.REASSONCODE BETWEEN '<reassonfrom>' AND  '<reassonto>'
AND CUSTOMERSDELETED.CUSTOMERCODE BETWEEN '<customerfrom>' AND '<customerto>'
AND ABS(CUSTOMERSDELETED.PROCESSED) IN (<statusprocessed>, <statusnotprocessed>)

UNION ALL

SELECT 
CUSTOMERSDELETED.USERID AS USERID,
USERS.USER_LOGIN AS USERNAME,
CUSTOMERSDELETED.CUSTOMERCODE,
CUSTOMERS.RAZON_SOCI AS CUSTOMERNAME,
CUSTOMERSDELETED.CANCELDATE,
CUSTOMERSDELETED.REASSONCODE,
TYPECUSTOMER_CANCELREASSONS.CANCELREASSON_NAME AS REASSONNAME,
(CASE WHEN PROCESSED = 0 THEN 'PENDIENTE' ELSE 'PROCESADO' END) AS STATUS
FROM <ownerdatabase>.DBO.CUSTOMERSDELETED
INNER JOIN <ownerdatabase>.DBO.USERS
ON CUSTOMERSDELETED.USERID = USERS.USER_ID
INNER JOIN <database>.DBO.GVA14 CUSTOMERS
ON CUSTOMERSDELETED.CUSTOMERCODE = CUSTOMERS.COD_CLIENT COLLATE Latin1_General_BIN
AND CUSTOMERSDELETED.POTENTIALCUSTOMER = 0
INNER JOIN <ownerdatabase>.DBO.TYPECUSTOMER_CANCELREASSONS
ON CUSTOMERSDELETED.REASSONCODE = TYPECUSTOMER_CANCELREASSONS.ID_CUSTOMERCANCELREASSON
WHERE CUSTOMERSDELETED.ID_COMPANY = <company>
AND CUSTOMERSDELETED.USERID BETWEEN <userfrom> AND <userto>
AND CUSTOMERSDELETED.CANCELDATE BETWEEN CONVERT(DATETIME, '<datefrom>', 102) AND CONVERT(DATETIME, '<dateto>', 102) 
AND CUSTOMERSDELETED.REASSONCODE BETWEEN '<reassonfrom>' AND  '<reassonto>'
AND CUSTOMERSDELETED.CUSTOMERCODE BETWEEN '<customerfrom>' AND '<customerto>'
AND ABS(CUSTOMERSDELETED.PROCESSED) IN (<statusprocessed>, <statusnotprocessed>)


SELECT 
POTENTIALCUSTOMERS.COD_CLIENT AS CUSTOMERCODE,
POTENTIALCUSTOMERS.RAZON_SOCI AS CUSTOMERNAME,
POTENTIALCUSTOMERS.COD_ZONA AS ZONECODE,
ZONES.NOMBRE_ZON AS ZONENAME,
POTENTIALCUSTOMERS.COD_PROVIN AS STATECODE,
STATES.NOMBRE_PRO AS STATENAME,
POTENTIALCUSTOMERS.COD_VENDED AS EMPLOYEECODE,
EMPLOYEES.NOMBRE_VEN AS EMPLOYEENAME
FROM <ownerdatabase>.DBO.POTENTIALCUSTOMERS
INNER JOIN <database>.DBO.GVA05 ZONES
ON POTENTIALCUSTOMERS.COD_ZONA = ZONES.COD_ZONA
INNER JOIN <database>.DBO.GVA18 STATES
ON POTENTIALCUSTOMERS.COD_PROVIN = STATES.COD_PROVIN 
INNER JOIN <database>.DBO.GVA23 EMPLOYEES
ON POTENTIALCUSTOMERS.COD_VENDED = EMPLOYEES.COD_VENDED
WHERE POTENTIALCUSTOMERS.COD_TANGO = ''
AND POTENTIALCUSTOMERS.ID_COMPANY = <company>
AND POTENTIALCUSTOMERS.COD_CLIENT BETWEEN '<customerfrom>' AND '<customerto>'
AND POTENTIALCUSTOMERS.COD_ZONA BETWEEN '<zonefrom>' AND '<zoneto>'
AND POTENTIALCUSTOMERS.COD_PROVIN BETWEEN '<statefrom>' AND '<stateto>'
AND POTENTIALCUSTOMERS.COD_VENDED BETWEEN '<employeefrom>' AND '<employeeto>'


SELECT 
CUSTOMERS.COD_CLIENT AS CUSTOMERCODE,
CUSTOMERS.RAZON_SOCI AS CUSTOMERNAME,
CUSTOMERS.COD_ZONA AS ZONECODE,
ZONES.NOMBRE_ZON AS ZONENAME,
CUSTOMERS.COD_PROVIN AS STATECODE,
STATES.NOMBRE_PRO AS STATENAME,
CUSTOMERS.COD_VENDED AS EMPLOYEECODE,
EMPLOYEES.NOMBRE_VEN AS EMPLOYEENAME
FROM <database>.DBO.GVA18 CUSTOMERS
INNER JOIN <database>.DBO.GVA05 ZONES
ON CUSTOMERS.COD_ZONA = ZONES.COD_ZONA
INNER JOIN <database>.DBO.GVA18 STATES
ON CUSTOMERS.COD_PROVIN = STATES.COD_PROVIN 
INNER JOIN <database>.DBO.GVA23 EMPLOYEES
ON CUSTOMERS.COD_VENDED = EMPLOYEES.COD_VENDED
WHERE CUSTOMERS.COD_TANGO = ''
AND CUSTOMERS.ID_COMPANY = <company>
AND CUSTOMERS.COD_CLIENT BETWEEN '<customerfrom>' AND '<customerto>'
AND CUSTOMERS.COD_ZONA BETWEEN '<zonefrom>' AND '<zoneto>'
AND CUSTOMERS.COD_PROVIN BETWEEN '<statefrom>' AND '<stateto>'
AND CUSTOMERS.COD_VENDED BETWEEN '<employeefrom>' AND '<employeeto>'